estimator: drone_target_pose_estimation
train:
  dataset_zip_file_name_training: drone_training_medium
  batch_training_size: 75
  accumulation_steps: 10
  epochs: 100
  beta_loss: 1
  scale_translation: 1
val:
  dataset_zip_file_name_validation: drone_validation_medium
  batch_validation_size: 30
  eval_freq: 1
test:
  dataset_zip_file_name_test: drone_validation_medium
  batch_test_size: 30
dataset:
  image_scale: 224
  download_data_gcp: False
  gcs_bucket: drone-pose-estimation
  pose_estimation_gcs_path: data
adam_optimizer:
  lr: 0.0001
  beta_1: 0.9
  beta_2: 0.999
checkpoint:
  load_dir_checkpoint: None
  save_frequency: 10
system:
  log_dir_system: /home/souranil/ai/research/ai-hw21-drone-pose-estimation-navigation/models
  # log_dir_system: "gs://drone-pose-estimation/out/medium-local"
  data_root: /home/souranil/ai/research/ai-hw21-drone-pose-estimation-navigation/data
