name: pose_estimation
channels:
    - defaults
    - pytorch
dependencies:
    - python=3.8
    - click=7.1.2
    - cudatoolkit=10.1
    - cudnn=7.6.5
    - flake8=3.8.3
    - isort=4.3.21
    - jupyter=1.0.0
    - pip=20.1.1
    - pytest=5.4.3
    - pytest-cov=2.10.0
    - pytorch=1.7.0
    - torchvision=0.8.1
    - docopt=0.6.2
    - black=19.10b
    - pyyaml=5.3.1 
    
    - pip:
        - kfp==1.0.4
        - easydict==1.9
        - tensorboardX==2.1