// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PostEstimation.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Protocolor {
  public static partial class PostEstimationService
  {
    static readonly string __ServiceName = "protocolor.PostEstimationService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Protocolor.ImageInfo> __Marshaller_protocolor_ImageInfo = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protocolor.ImageInfo.Parser));
    static readonly grpc::Marshaller<global::Protocolor.PoseEstimationResponse> __Marshaller_protocolor_PoseEstimationResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protocolor.PoseEstimationResponse.Parser));

    static readonly grpc::Method<global::Protocolor.ImageInfo, global::Protocolor.PoseEstimationResponse> __Method_GetPoseEstimation = new grpc::Method<global::Protocolor.ImageInfo, global::Protocolor.PoseEstimationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPoseEstimation",
        __Marshaller_protocolor_ImageInfo,
        __Marshaller_protocolor_PoseEstimationResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Protocolor.PostEstimationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PostEstimationService</summary>
    [grpc::BindServiceMethod(typeof(PostEstimationService), "BindService")]
    public abstract partial class PostEstimationServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Protocolor.PoseEstimationResponse> GetPoseEstimation(global::Protocolor.ImageInfo request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PostEstimationService</summary>
    public partial class PostEstimationServiceClient : grpc::ClientBase<PostEstimationServiceClient>
    {
      /// <summary>Creates a new client for PostEstimationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PostEstimationServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PostEstimationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PostEstimationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PostEstimationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PostEstimationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Protocolor.PoseEstimationResponse GetPoseEstimation(global::Protocolor.ImageInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPoseEstimation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Protocolor.PoseEstimationResponse GetPoseEstimation(global::Protocolor.ImageInfo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPoseEstimation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Protocolor.PoseEstimationResponse> GetPoseEstimationAsync(global::Protocolor.ImageInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPoseEstimationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Protocolor.PoseEstimationResponse> GetPoseEstimationAsync(global::Protocolor.ImageInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPoseEstimation, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PostEstimationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PostEstimationServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PostEstimationServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetPoseEstimation, serviceImpl.GetPoseEstimation).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PostEstimationServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetPoseEstimation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protocolor.ImageInfo, global::Protocolor.PoseEstimationResponse>(serviceImpl.GetPoseEstimation));
    }

  }
}
#endregion
