# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostEstimation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PostEstimation.proto',
  package='protocolor',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14PostEstimation.proto\x12\nprotocolor\"\x1a\n\tImageInfo\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x97\x01\n\x16PoseEstimationResponse\x12=\n\x16\x64roneTransformPosition\x18\x03 \x01(\x0b\x32\x1d.protocolor.TransformPosition\x12>\n\x17targetTransformPosition\x18\x04 \x01(\x0b\x32\x1d.protocolor.TransformPosition\"4\n\x11TransformPosition\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x32g\n\x15PostEstimationService\x12N\n\x11GetPoseEstimation\x12\x15.protocolor.ImageInfo\x1a\".protocolor.PoseEstimationResponseb\x06proto3'
)




_IMAGEINFO = _descriptor.Descriptor(
  name='ImageInfo',
  full_name='protocolor.ImageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='protocolor.ImageInfo.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=62,
)


_POSEESTIMATIONRESPONSE = _descriptor.Descriptor(
  name='PoseEstimationResponse',
  full_name='protocolor.PoseEstimationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='droneTransformPosition', full_name='protocolor.PoseEstimationResponse.droneTransformPosition', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targetTransformPosition', full_name='protocolor.PoseEstimationResponse.targetTransformPosition', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=216,
)


_TRANSFORMPOSITION = _descriptor.Descriptor(
  name='TransformPosition',
  full_name='protocolor.TransformPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='protocolor.TransformPosition.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='protocolor.TransformPosition.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='protocolor.TransformPosition.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=270,
)

_POSEESTIMATIONRESPONSE.fields_by_name['droneTransformPosition'].message_type = _TRANSFORMPOSITION
_POSEESTIMATIONRESPONSE.fields_by_name['targetTransformPosition'].message_type = _TRANSFORMPOSITION
DESCRIPTOR.message_types_by_name['ImageInfo'] = _IMAGEINFO
DESCRIPTOR.message_types_by_name['PoseEstimationResponse'] = _POSEESTIMATIONRESPONSE
DESCRIPTOR.message_types_by_name['TransformPosition'] = _TRANSFORMPOSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageInfo = _reflection.GeneratedProtocolMessageType('ImageInfo', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEINFO,
  '__module__' : 'PostEstimation_pb2'
  # @@protoc_insertion_point(class_scope:protocolor.ImageInfo)
  })
_sym_db.RegisterMessage(ImageInfo)

PoseEstimationResponse = _reflection.GeneratedProtocolMessageType('PoseEstimationResponse', (_message.Message,), {
  'DESCRIPTOR' : _POSEESTIMATIONRESPONSE,
  '__module__' : 'PostEstimation_pb2'
  # @@protoc_insertion_point(class_scope:protocolor.PoseEstimationResponse)
  })
_sym_db.RegisterMessage(PoseEstimationResponse)

TransformPosition = _reflection.GeneratedProtocolMessageType('TransformPosition', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORMPOSITION,
  '__module__' : 'PostEstimation_pb2'
  # @@protoc_insertion_point(class_scope:protocolor.TransformPosition)
  })
_sym_db.RegisterMessage(TransformPosition)



_POSTESTIMATIONSERVICE = _descriptor.ServiceDescriptor(
  name='PostEstimationService',
  full_name='protocolor.PostEstimationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=272,
  serialized_end=375,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPoseEstimation',
    full_name='protocolor.PostEstimationService.GetPoseEstimation',
    index=0,
    containing_service=None,
    input_type=_IMAGEINFO,
    output_type=_POSEESTIMATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSTESTIMATIONSERVICE)

DESCRIPTOR.services_by_name['PostEstimationService'] = _POSTESTIMATIONSERVICE

# @@protoc_insertion_point(module_scope)
