# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostEstimation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PostEstimation.proto',
  package='protocolor',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14PostEstimation.proto\x12\nprotocolor\"\x1d\n\x0c\x43urrentColor\x12\r\n\x05\x63olor\x18\x01 \x01(\t\"\x19\n\x08NewColor\x12\r\n\x05\x63olor\x18\x01 \x01(\t2T\n\x0e\x43olorGenerator\x12\x42\n\x0eGetRandomColor\x12\x18.protocolor.CurrentColor\x1a\x14.protocolor.NewColor\"\x00\x62\x06proto3'
)




_CURRENTCOLOR = _descriptor.Descriptor(
  name='CurrentColor',
  full_name='protocolor.CurrentColor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='protocolor.CurrentColor.color', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=65,
)


_NEWCOLOR = _descriptor.Descriptor(
  name='NewColor',
  full_name='protocolor.NewColor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='protocolor.NewColor.color', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['CurrentColor'] = _CURRENTCOLOR
DESCRIPTOR.message_types_by_name['NewColor'] = _NEWCOLOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CurrentColor = _reflection.GeneratedProtocolMessageType('CurrentColor', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTCOLOR,
  '__module__' : 'PostEstimation_pb2'
  # @@protoc_insertion_point(class_scope:protocolor.CurrentColor)
  })
_sym_db.RegisterMessage(CurrentColor)

NewColor = _reflection.GeneratedProtocolMessageType('NewColor', (_message.Message,), {
  'DESCRIPTOR' : _NEWCOLOR,
  '__module__' : 'PostEstimation_pb2'
  # @@protoc_insertion_point(class_scope:protocolor.NewColor)
  })
_sym_db.RegisterMessage(NewColor)



_COLORGENERATOR = _descriptor.ServiceDescriptor(
  name='ColorGenerator',
  full_name='protocolor.ColorGenerator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=94,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRandomColor',
    full_name='protocolor.ColorGenerator.GetRandomColor',
    index=0,
    containing_service=None,
    input_type=_CURRENTCOLOR,
    output_type=_NEWCOLOR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COLORGENERATOR)

DESCRIPTOR.services_by_name['ColorGenerator'] = _COLORGENERATOR

# @@protoc_insertion_point(module_scope)
