# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PostEstimation_pb2 as PostEstimation__pb2


class PostEstimationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPoseEstimation = channel.unary_unary(
                '/protocolor.PostEstimationService/GetPoseEstimation',
                request_serializer=PostEstimation__pb2.ImageInfo.SerializeToString,
                response_deserializer=PostEstimation__pb2.PoseEstimationResponse.FromString,
                )


class PostEstimationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPoseEstimation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostEstimationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPoseEstimation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoseEstimation,
                    request_deserializer=PostEstimation__pb2.ImageInfo.FromString,
                    response_serializer=PostEstimation__pb2.PoseEstimationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protocolor.PostEstimationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PostEstimationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPoseEstimation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protocolor.PostEstimationService/GetPoseEstimation',
            PostEstimation__pb2.ImageInfo.SerializeToString,
            PostEstimation__pb2.PoseEstimationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
